# Generated by Django 4.1.1 on 2022-09-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="movie", options={"ordering": ["-rating"]},),
        migrations.AddField(
            model_name="movie",
            name="genre",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="released_at",
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
    ]
