# Generated by Django 4.1.1 on 2022-09-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_alter_movie_options_movie_genre_movie_released_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="released_at",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
